sulu_notifier:
    channels:
        'chat/fakechat+email':
            - Sulu\Page\Domain\Event\PageWorkflowTransitionAppliedEvent
            - Sulu\Article\Domain\Event\ArticleWorkflowTransitionAppliedEvent
